apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure.yaml
  - runtime.yaml
  - observability.yaml
  - metrics-discovery.yaml
  - networking-routes.yaml
  - resilience.yaml

configMapGenerator:
  - name: keycloak-realm
    files:
      - mayabanque-realm.json
