quarkus.application.name=consumer-psp
quarkus.http.port=8080
quarkus.rest-client.mock-wero.url=http://mock-wero:8080
quarkus.smallrye-health.root-path=/health
quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317
quarkus.otel.exporter.otlp.protocol=grpc
quarkus.otel.simple=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.log.console.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p service=consumer-psp traceId=%X{traceId} spanId=%X{spanId} [%c{2.}] (%t) %s%e%n
