quarkus.http.port=8080
quarkus.rest-client.consumer-psp.url=http://consumer-psp:8080
quarkus.rest-client.consumer-psp.connect-timeout=1000
quarkus.rest-client.consumer-psp.read-timeout=2000
quarkus.rest-client.sct-inst-status.url=http://mock-sct-inst:8080
quarkus.rest-client.sct-inst-status.connect-timeout=1000
quarkus.rest-client.sct-inst-status.read-timeout=2000
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=mayabanque
quarkus.datasource.password=mayabanque
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/wero
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/health
