quarkus.http.port=8080
quarkus.rest-client.consumer-psp.url=http://consumer-psp:8080
quarkus.rest-client.consumer-psp.connect-timeout=1000
quarkus.rest-client.consumer-psp.read-timeout=2000
quarkus.rest-client.sct-inst-status.url=http://mock-sct-inst:8080
quarkus.rest-client.sct-inst-status.connect-timeout=1000
quarkus.rest-client.sct-inst-status.read-timeout=2000
quarkus.rest-client.consent-service.url=http://consent-service:8080
quarkus.rest-client.consent-service.connect-timeout=1000
quarkus.rest-client.consent-service.read-timeout=2000
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:mayabanque}
quarkus.datasource.password=${DB_PASSWORD:mayabanque}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/${DB_NAME:wero}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/health
kafka.bootstrap.servers=kafka:9092
wero.events.topic=payment-events
wero.outbox.batch-size=50
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/mayabanque
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles
