quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=mayabanque
quarkus.datasource.password=mayabanque
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/wero
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/health
kafka.bootstrap.servers=kafka:9092
wero.events.topic=payment-events
wero.audit.group-id=payment-audit-v1
