quarkus.application.name=event-audit-service
quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:mayabanque}
quarkus.datasource.password=${DB_PASSWORD:mayabanque}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/${DB_NAME:wero}
quarkus.datasource.jdbc.telemetry=true
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/health
kafka.bootstrap.servers=kafka:9092
wero.events.topic=payment-events
wero.audit.group-id=payment-audit-v1
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/mayabanque
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.token.issuer=any
quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317
quarkus.otel.exporter.otlp.protocol=grpc
quarkus.otel.simple=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.log.console.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p service=event-audit-service traceId=%X{traceId} spanId=%X{spanId} [%c{2.}] (%t) %s%e%n
