quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:mayabanque}
quarkus.datasource.password=${DB_PASSWORD:mayabanque}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/${DB_NAME:wero}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/health
kafka.bootstrap.servers=kafka:9092
wero.events.topic=payment-events
wero.audit.group-id=payment-audit-v1
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/mayabanque
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles
